sonar.organization=carminesgariglia
sonar.projectKey=CarmineSgariglia_BugBoard26
sonar.projectName=BugBoard26
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.sources=backend
sonar.tests=backend/apps/bugboardapi/tests
sonar.inclusions=backend/**/*.py
sonar.test.inclusions=backend/apps/bugboardapi/tests/**/*.py
sonar.exclusions=backend/media/**,backend/coverage/**,backend/**/__pycache__/**,backend/**/*.pyc,backend/.coverage,backend/apps/bugboardapi/migrations/**

sonar.python.coverage.reportPaths=backend/coverage/coverage.xml
