sonar.organization=carminesgariglia
sonar.projectKey=CarmineSgariglia_BugBoard26
sonar.projectName=BugBoard26

sonar.sources=backend/apps,backend/config,frontend/src
sonar.tests=backend/apps/bugboardapi/tests,frontend/src,frontend/tests/e2e
sonar.test.inclusions=backend/apps/bugboardapi/tests/**/*.py,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/tests/e2e/**/*.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/playwright-report/**,**/test-results/**,backend/media/**,backend/apps/bugboardapi/tests/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx

sonar.python.coverage.reportPaths=backend/coverage/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
