# Generated by Django 5.2.11 on 2026-02-24 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_issues', through='core.IssueAssignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(related_name='issues', through='core.IssueTag', to='core.tag'),
        ),
    ]
