# Generated by Django 5.2.11 on 2026-03-01 20:12

from django.db import migrations, models


def rename_critical_to_urgent(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")
    Issue.objects.filter(priority="CRITICAL").update(priority="URGENT")


def rename_urgent_to_critical(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")
    Issue.objects.filter(priority="URGENT").update(priority="CRITICAL")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_issue_assignees_issue_tags'),
    ]

    operations = [
        migrations.RunPython(rename_critical_to_urgent, rename_urgent_to_critical),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=16),
        ),
    ]
