# Generated by Django 5.2.11 on 2026-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0003_alter_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(db_column='attemptCount', default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, db_column='lastAttemptAt', null=True),
        ),
    ]
