# Generated by Django 5.2.12 on 2026-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0004_passwordresetotp_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
