# Generated by Django 5.2.12 on 2026-03-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0006_issueimage_alter_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueImage',
        ),
    ]
