# Generated by Django 5.2.12 on 2026-03-07 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0009_rename_userprofile_userimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedTokenSession',
            fields=[
                ('sid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_column='expiresAt')),
                ('revoked_at', models.DateTimeField(auto_now_add=True, db_column='revokedAt')),
                ('user', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoked_token_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RevokedTokenSession',
                'indexes': [models.Index(fields=['expires_at'], name='revoked_session_exp_idx')],
            },
        ),
    ]
