# Generated by Django 5.2.12 on 2026-03-08 12:00

import hashlib

from django.db import migrations, models


def hash_existing_otp_codes(apps, schema_editor):
    PasswordResetOTP = apps.get_model("bugboardapi", "PasswordResetOTP")

    for otp in PasswordResetOTP.objects.all().only("otp_id", "code"):
        raw_code = otp.code or ""
        if len(raw_code) == 6 and raw_code.isdigit():
            otp.code = hashlib.sha256(raw_code.encode("utf-8")).hexdigest()
            otp.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0010_revokedtokensession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.RunPython(hash_existing_otp_codes, migrations.RunPython.noop),
    ]
