# Generated by Django 5.2.12 on 2026-03-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0012_normalize_tag_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='is_admin',
        ),
    ]
