# Generated by Django 5.2.12 on 2026-03-09 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0014_rename_userimage_userprofileimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notification_users', through='bugboardapi.NotifyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
