# Generated by Django 5.2.12 on 2026-03-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0015_notification_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
    ]
