# Generated by Django 5.2.12 on 2026-03-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bugboardapi", "0017_notification_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmembership",
            name="role",
        ),
    ]
