# Generated by Django 5.2.12 on 2026-03-09 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugboardapi", "0018_remove_projectmembership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(related_name="projects", through="bugboardapi.ProjectMembership", to=settings.AUTH_USER_MODEL),
        ),
    ]
