# Generated by Django 5.2.12 on 2026-03-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0019_project_members_many_to_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
    ]
