# Generated by Django 5.2.12 on 2026-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0020_remove_issue_closed_at_remove_issue_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_xor_target',
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='message',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
