# Generated by Django 5.2.12 on 2026-03-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugboardapi', '0022_alter_notification_type_project_unassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueevent',
            name='message',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
